### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by raphaelduartepinheiro** [rajeshwarpatlolla/ionic-datepicker#28]
Hello! 
The months, days of week, and GUI are in english, is on plan to localize these objects?

**Comment by rajeshwarpatlolla** [comment]
For now, i have few other tasks/bugs in my list for the next immediate release. But localisation needs one more additional plugin. I think it might make this component bit heavy. Any suggestions to get the perfect solution is welcome. And thanks for this suggestion too.

**Comment by seppsepp** [comment]
Suggestion: Add a setter to enable users to pass translations into the service. Same for the yearsList.

**Comment by raphaelduartepinheiro** [comment]
I agree with @seppsepp suggestion. It's easy to implement and the file size would be pretty much the same.

**Comment by willianbs** [comment]
Or you can use the angularjs locale format thais is easier to implement: https://code.angularjs.org/1.0.3/i18n/

**Comment by rajeshwarpatlolla** [comment]
Thanks a lot for the link @willianbs. i will check this out when ever it is possible for me to do so.

**Comment by rajeshwarpatlolla** [comment]
Please use the new version i.e. `v0.7.0` This bug has been fixed. I found a simple a way of getting Localization. Please check this latest version.

**Comment by willianbs** [comment]
Hi, we still can't translate the weekdays, just to remember :)

**Comment by rajeshwarpatlolla** [comment]
Do you mean S,M,T,W,...?

**Comment by willianbs** [comment]
Yep
