### ISSUE TITLE
clicking empty cells causes JS error

### ISSUE THREAD

**Issue by justinobney** [rajeshwarpatlolla/ionic-datepicker#59]
![Error image](https://photos-1.dropbox.com/t/2/AACAu019Eza4AJ9XrUiz-bBn8w9yshlKihjmyr-nyC--AA/12/2857953/png/32x32/1/1440021600/0/2/2015-08-19%2015_32_23-Developer%20Tools%20-%20http___rajeshwarpatlolla.github.io_DatePickerForIonicFramework.png/COG3rgEgASACIAMgBCAFIAYgBygBKAIoBw/1CXsElUC8d6xCna2z2YQN7nz8aUCbLHwFU1L-gM8DcE?size=1280x960&size_mode=2)

**Comment by rajeshwarpatlolla** [comment]
I can't see any image or any error in the demo. Please use this link. http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker

**Comment by justinobney** [comment]
Still getting issue: https://db.tt/uCLsmIHr

In the demo, the 31st is orphaned in a new row  (only date left in month) I am simply clicking where the 1st of the next month would be, if it were rendered. See the cursor position in the image.

**Comment by rajeshwarpatlolla** [comment]
I can see it now. Thanks for finding this issue. I am working on a new version of this component. I will try to fix this issue in that new version. May be you can expect that new new version in the next few hours.

**Comment by rajeshwarpatlolla** [comment]
This bug has been fixed. You can the new version i.e. v0.8.0.

**Comment by rajild** [comment]
This issue still persist in example given at below URL:
http://rajeshwarpatlolla.github.io/DatePickerForIonicFramework/demo/#/tab/date-picker

See below image:
![image](https://cloud.githubusercontent.com/assets/6926340/9829911/544531fe-5937-11e5-94e0-1bab54b3c926.png)
  
Steps:
1)  open date picker.
2)  click on empty cell at the div i shown in above image.
3)  date will set to nan and after setting this,  date picker is not opening.

is there any way to solve this?

**Comment by rajeshwarpatlolla** [comment]
Yes, you are right. I can see it there. I will check the source code and will let you know, once it is fixed.

**Comment by rajild** [comment]
Thanks a lot for quick reply.  I think you can fix it by skipping this div for empty dates.  Awaiting your reply.

Also,  for pop-up mode,  the date picker is quiet slow.  Due to this multiple instances are opening when user clicks multiple times this also leads to application crash.  I am going to try using model as suggested by you in another post.

**Comment by rajeshwarpatlolla** [comment]
Issue resolved. Code pushed to master branch. Please take a look at [this commit](https://github.com/rajeshwarpatlolla/ionic-datepicker/commit/c5fa80700864848827ccaf719b900b95b259b093).
