### ISSUE TITLE
Very slow on Android

### ISSUE THREAD

**Issue by borNfreee** [rajeshwarpatlolla/ionic-datepicker#82]
Hi,

on my Nexus 5 if I click to the input, there is a delay about 1-2 seconds before datepicker is displayed.
When I click to 'set' button to choose the date - again, there is a 1-2 seconds delay.

Other elements work fast.

**Comment by rajeshwarpatlolla** [comment]
Have you tried using the modal instead of the popup? That was faster than the popup. But still i tried in few devices, there is no considerable delay of 1-2 seconds. May be you can give it a try using the modal.

**Comment by borNfreee** [comment]
I will test with a modal and will post results here, but I prefer a popup.
You can test delay with android 5.1.1 Nexus 5 emulator.

**Comment by borNfreee** [comment]
I confirm that Modal works faster, but what's the reason?

**Comment by rconesasorolla** [comment]
The real problem is the years list, when the app loads years list takes a few seconds in my case

**Comment by rajeshwarpatlolla** [comment]
I don't think year list is leading to this delay. When we use modal, it's not even taking fraction of seconds to load. But if we use popup then only it is taking about a second to show it.

**Comment by thm1118** [comment]
Modal  is full screen in mobile , client user maybe treat as a view ,and will use back button to cancel date select ; and pop can redefine button style  more easy. but Modal's button style use hard code.
so, that is why somebody like me like use pop

**Comment by rynangeles** [comment]
i also encounter the slowness on one of my low-end devices. Looking at the source i would suggest to use controller as syntax and scope is a bit over used.

**Comment by rajeshwarpatlolla** [comment]
Thanks for the suggestion @rynangeles.

**Comment by Chuckv01** [comment]
+1, I am also experiencing slowness with the popup on android. Any fix for this in the works?

**Comment by rynangeles** [comment]
the slowness is all because of digest of angular. i also tried ui-bootstrap datepicker and it has the same slowness. One of this day ill try to create a slim and simple impementation of datepicker for angular mobile.

**Comment by kerosin** [comment]
issuing same slowness on Android (Note 3), about 2 seconds

**Comment by gaurav-chandra** [comment]
Same slowness on Android 5 on Lenovo A6000. In my case the user taps more then once thinking that the tap was not proper.

**Comment by rajeshwarpatlolla** [comment]
You can disable the button when the user clicks on the button for the first time. This may avoid some confusion for the users.

**Comment by borNfreee** [comment]
@rajeshwarpatlolla it's a workaround, not a solution

**Comment by rajeshwarpatlolla** [comment]
Yes, you are right @borNfreee.

**Comment by gaurav-chandra** [comment]
I did a small hack. I am referring to the mimised version of the code.

1. I removed the template caching code for popup and converted that into an html file ```/lib/ionic-datepicker/ionic-datepicker-popup.html```

2. In my app.js, I created a loop for template caching:
```
var templates = [
            "lib/ionic-datepicker/ionic-datepicker-popup.html"
        ];

        for(i=0;i<templates.length;i++){
            var template = templates[i];
            if ($templateCache.get(template)){
                return; //prevent the prefetching if the template is already in the cache
            }
            $http.get(template).success(function (t) {
                console.log('-----------------------got the datepicker template');
                $templateCache.put(template, t);
            });
        }
```
3. Then at the line where the ```ionic-datepicker-popup.html``` is called, I am calling ```/lib/ionic-datepicker/ionic-datepicker-popup.html```

This has resulted in shaving off atleast 2 seconds for me. The modal is indeed fast but I cannot go to modal way dues to client's restriction.

**Comment by thinhnk** [comment]
Same snowless on Xiaomi MI3w with popup. any solutions for this?

**Comment by sreemohan003** [comment]
Please any one give the model code so that i can use help me out

**Comment by rajeshwarpatlolla** [comment]
All you need to do is, in the object you are passing to the datepicker directive just say 
> templateType : ''modal"

**Comment by sreemohan003** [comment]
where i need to change templateType : ''modal" please help  me out

On Sun, Feb 28, 2016 at 12:14 PM, Rajeshwar <notifications@github.com>
wrote:

> All you need to do is, in the object you are passing to the datepicker
> directive just say
>
> templateType : ''modal"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/82#issuecomment-189800255>
> .
>



-- 
thanks and regards,
R.Mohanraj
7760342142

**Comment by rajeshwarpatlolla** [comment]
Please read the [documentation](https://github.com/rajeshwarpatlolla/ionic-datepicker#how-to-use)

**Comment by sreemohan003** [comment]
thanks its working

On Sun, Feb 28, 2016 at 12:24 PM, Rajeshwar <notifications@github.com>
wrote:

> Please read the documentation
> <https://github.com/rajeshwarpatlolla/ionic-datepicker#how-to-use>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/82#issuecomment-189803763>
> .
>



-- 
thanks and regards,
R.Mohanraj
7760342142

**Comment by sreemohan003** [comment]
Invite
    

    
        

            
                
                    
                        
                    
                    
                                                

                


                
                    Dear rajeshwarpatlolla/ionic-datepicker, 

                    
                        I found a simple way to save on all purchases. CashbackURL.in is just a one click process to earn cashback.
                        Before buying from any of the 500+ Indian online stores, just open www.cashbackURL.in and search for store or copy paste product URL. And, continue buying normally from the store. 
                        Cashback gets tracked and you can redeem the amount for either mobile recharge or cash payment. 
                    

                    
                        Click here to Activate your Account
                    

                    ( Since I'm referring you, clicking on the above link creates an account instantly. And, you can immediately start earning on cashbackURL )

                    
                        Cheers,
                        sree mohan 
                    
                

                This email has been sent by cashbackURL on behalf of your friend, sree mohan. 
                    Click here to Unsubscribe if you don't want to receive any emails in future.

                
            


            © LOCUS Web Services Pvt. Ltd.,2nd Floor, Pochampally House, 1-10-72/A/2, above Nike Showroom, 
                Beside Nalli Silks, SP Road, Begumpet,Telangana, India.

**Comment by rajeshwarpatlolla** [comment]
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.

**Comment by koreem** [comment]
I'm still experiencing a delay of 2 seconds when I open the datepicker (popup). How can I fix this?

**Comment by foaudkajj** [comment]
I am getting unknown provider after adding ionicDatePickerProvider provider to my .config method while every another thing is correct configured .
